# Name of the workflow
name: Build

# Controls what will trigger the workflow.
# Change it to your needs.
on:
 # A new push to the "main" branch.
 push:
   branches: [ "main" ]
 # A new pull request to the "main" branch.
 pull_request:
   branches: [ "main" ]
 # Allows to trigger the workflow from GitHub interfaces.
 workflow_dispatch:

# A single workflow can have multiple jobs.
jobs:
 # 'A new job is defined with the name: "build_ios"
 build_ios:
   # Defines what operating system will be used for the actions.
   # For iOS, we have to use macOS GitHub-Hosted Runner.
   runs-on: macos-12
   # Defines what step should be passed for successful run
   steps:
     # Checkout to the selected branch
     - name: Checkout
       uses: actions/checkout@v3
     # Download and install flutter packages
     - name: Install Flutter
       uses: subosito/flutter-action@v2
       with:
         # Define which stable flutter version should be used
         flutter-version: "3.7.3"
         channel: 'stable'
         # Enables cache for flutter packages
         # Speed up the process
         cache: true
     # Get Flutter project dependencies
     - name: Get dependencies
       run: flutter pub get
     - name: Build unsigned iOS app
       run: flutter build ipa --export-options-plist=ios/exportOptions.plist